### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by LedArts** [chrisparton1991/xmas-2016#1]
hello sir, i am trying your code but having this error please help and guide me.

Arduino: 1.8.0 (Windows 7), Board: "Arduino/Genuino Uno"

C:\Program Files\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\Arduino\hardware -hardware C:\Users\Pankaj\AppData\Local\Arduino15\packages -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -tools C:\Users\Pankaj\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files\Arduino\libraries -libraries D:\Arduino Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10800 -build-path C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\Pankaj\Downloads\Compressed\Pixal 2801 project\xmas-2016\xmas-2016-master\Animation\Animation.ino
C:\Program Files\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files\Arduino\hardware -hardware C:\Users\Pankaj\AppData\Local\Arduino15\packages -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -tools C:\Users\Pankaj\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files\Arduino\libraries -libraries D:\Arduino Sketches\libraries -fqbn=arduino:avr:uno -ide-version=10800 -build-path C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\Pankaj\Downloads\Compressed\Pixal 2801 project\xmas-2016\xmas-2016-master\Animation\Animation.ino
Using board 'uno' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\Animation.ino.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\Animation.ino.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\build_effect.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\debug_utils.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\effect_utils.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\fill_effect.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\flash_effect.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\line_effect.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\repel_lines_effect.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\FastLED.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\colorpalettes.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\colorutils.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\hsv2rgb.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\lib8tion.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\noise.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\power_mgt.cpp" -o "nul"
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "D:\Arduino Sketches\libraries\FastLED-3.1.0\wiring.cpp" -o "nul"
Generating function prototypes...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\Animation.ino.cpp" -o "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Program Files\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10800 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-IC:\Program Files\Arduino\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\Arduino\hardware\arduino\avr\variants\standard" "-ID:\Arduino Sketches\libraries\FastLED-3.1.0" "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\Animation.ino.cpp" -o "C:\Users\Pankaj\AppData\Local\Temp\arduino_build_592395\sketch\Animation.ino.cpp.o"
In file included from C:\Users\Pankaj\Downloads\Compressed\Pixal 2801 project\xmas-2016\xmas-2016-master\Animation\Animation.ino:2:0:

globals.h:49: error: 'CRGBArray' does not name a type

 extern CRGBArray<LED_COUNT> leds;

        ^

Animation:12: error: 'CRGBArray' does not name a type

 CRGBArray<LED_COUNT> leds;

 ^

C:\Users\Pankaj\Downloads\Compressed\Pixal 2801 project\xmas-2016\xmas-2016-master\Animation\Animation.ino: In function 'void setup()':

Animation:18: error: 'leds' was not declared in this scope

   FastLED.addLeds<UCS1903B, DATA_PIN, BRG>(leds, LED_COUNT).setCorrection(TypicalSMD5050);

                                            ^

C:\Users\Pankaj\Downloads\Compressed\Pixal 2801 project\xmas-2016\xmas-2016-master\Animation\Animation.ino: In function 'void loop()':

Animation:27: error: 'leds' was not declared in this scope

   fill_solid(leds, LED_COUNT, Color::Black);

              ^

Using library FastLED-3.1.0 at version 3.1.0 in folder: D:\Arduino Sketches\libraries\FastLED-3.1.0 
exit status 1
'CRGBArray' does not name a type

**Comment by chrisparton1991** [comment]
Hi @LedArts, thanks for taking an interest :)

I downloaded both the 3.1.0 and 3.1.3 releases from https://github.com/FastLED/FastLED/releases, and did global searches for `CRGBArray` in both of them. 3.1.0 doesn't have this class, so you'll have to upgrade your FastLED library to v3.1.3 for this sketch to work.

Can you try downloading the latest release of FastLED from https://github.com/FastLED/FastLED/releases/tag/v3.1.3 and use that instead of 3.1.0?

Good luck!

**Comment by LedArts** [comment]
ok sir,............

thanx a lot.

one more thing sir.....do u have more interesting effects of fast led or neo pixel??
if yes please give me the examples...i need it.

**Comment by chrisparton1991** [comment]
No problem. I don't have anything like that, I'm afraid.
